# Generated by Django 5.0.6 on 2024-08-03 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microservice_app', '0004_gender_province_role_status_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
