# Generated by Django 5.0.6 on 2024-08-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservice_app', '0005_remove_user_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
